variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: "1"

windows:stable:
  script:
    - cargo build --verbose
    - cargo test --verbose
  stage: build
  tags:
    - tox
    - windows

macos:stable:
  script:
    - cargo build --verbose
    - cargo test --verbose
  stage: build
  tags:
    - tox
    - macos

.linux_template: &linux_script
  ### run build, test and doc
  - |
    cargo build --verbose
    cargo test --verbose
    cargo doc

linux:v1-40-0:
  image: rustdocker/rust:1.40.0
  script: *linux_script
  after_script:
    ### measure code coverage and upload to coveralls.io
    - |
      CARGO_TARGET_DIR=target/ cargo install --force cargo-travis || echo "cargo-travis has been already installed"
      export PATH=$HOME/.cargo/bin:$PATH
      export TRAVIS_JOB_ID=$CI_BUILD_ID
      cargo coveralls
  stage: build
  tags:
    - tox
    - docker

linux:stable:
  image: rustdocker/rust:stable
  script: *linux_script
  stage: build
  tags:
    - tox
    - docker

linux:beta:
  allow_failure: true
  image: rustdocker/rust:beta
  script: *linux_script
  stage: build
  tags:
    - tox
    - docker

linux:nightly:
  allow_failure: true
  image: rustdocker/rust:nightly
  script:
    ### run build, test and doc
    - |
      cargo build --verbose --features "clippy"
      cargo test --verbose --features "clippy"
      cargo doc
  stage: build
  tags:
    - tox
    - docker

other:kcov-and-check-commit-message:
  image: rustdocker/rust:1.40.0
  script:
    ### export sha
    - |
      if [[ -z $CI_COMMIT_BEFORE_SHA ]]
      then
        export CI_COMMIT_BEFORE_SHA=$(git rev-parse HEAD^)
      fi
      export CI_COMMIT_RANGE="$CI_COMMIT_BEFORE_SHA..$CI_COMMIT_SHA"

    ### Script for verifying conformance to commit message format of commits in commit
    ### range supplied.
    - |
      ./scripts/verify-commit-messages.sh "$CI_COMMIT_RANGE"

    ### export env variables and create dirs
    - |
      export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
      export KCOV_DIR=`pwd`/kcov && mkdir -pv $KCOV_DIR
      export ROOT_DIR=`pwd`
      rm -rf target/kcov || echo 'target/kcov not exist'

    ### build kcov for 1.40.0
    - |
      sudo apt-get remove kcov -y || echo 'ok'
      sudo apt-get -o dir::cache::archives="$APT_CACHE_DIR" update -yq
      sudo apt-get -o dir::cache::archives="$APT_CACHE_DIR" install libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev -yq
      cd $KCOV_DIR && git clone https://github.com/SimonKagstrom/kcov || echo 'kcov exist'
      cd kcov && cmake . && make && make install || echo 'kcov exist'
      cd $ROOT_DIR

    ### remove target directory
    - |
      rm -rf $ROOT_DIR/target/

    ### run test for build test executables
    - |
      cargo test --verbose

    ### run verify, merge code coverage and upload to codecov.io
    - |
      for file in $ROOT_DIR/target/debug/deps/tox-*[^\.d]
      do
        mkdir -pv $ROOT_DIR/target/cov/$(basename $file)
        kcov --exclude-pattern=$HOME/.cargo,/usr/lib --verify $ROOT_DIR/target/cov/$(basename $file) $file
        bash <(curl -s https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN -s $ROOT_DIR/target/cov/$(basename $file) && echo "Uploaded code coverage" || echo "Not uploaded code coverage"
      done

  stage: build
  tags:
    - tox
    - docker
