language: rust
os:
  - linux
  - osx
rust:
  - 1.40.0
  - stable

sudo: false
env:
  global:
    - RUST_BACKTRACE=1

branches:
  except:
    - /test.*/

script:
  - cargo build
  - cargo test
  - cargo doc

matrix:
  include:
    - name: check_commit_msg
      os: linux
      language: minimal
      script:
        - ./scripts/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE"

    - name: clippy
      os: linux
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --verbose --all --tests

    - name: coverage
      os: linux
      rust: stable
      sudo: required
      addons: # needed for `cargo install cargo-travis`
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake
          sources:
            - kalakris-cmake
      cache:
        directories:
          - /home/travis/.cargo
          - /home/travis/build/tox-rs/tox/target/kcov-master
      before_cache:
        - rm -rf /home/travis/.cargo/registry
      install:
        - cargo install cargo-update --debug || echo "cargo-update has been already installed"
        - cargo install-update -i cargo-travis
      script:
        - mkdir -p target # fix for cargo-coveralls
        - cargo coveralls
